/**
 * AssignTubes Actions
 */

const SCREEN_APPENDIX = '_AT'

export const  SET_CURRENT_PICKLIST = 'SET_CURRENT_PICKLIST' + SCREEN_APPENDIX;

export const SET_PARTS = 'SET_PARTS' + SCREEN_APPENDIX;

export const SET_LOADING_PARTS = 'SET_LOADING_PARTS' + SCREEN_APPENDIX;

export const QUERY_APPEND_BARCODE_TO_PART = 'QUERY_APPEND_BARCODE_TO_PART' + SCREEN_APPENDIX;
export const APPEND_BARCODE_TO_PART = 'APPEND_BARCODE_TO_PART' + SCREEN_APPENDIX;

export const SET_FOCUSED_PART_INDEX = 'SET_FOCUSED_PART_INDEX' + SCREEN_APPENDIX;

export const GET_PARTS_W_CONTAINER_IN_PICKLIST = 'GET_PARTS_W_CONTAINER_IN_PICKLIST' + SCREEN_APPENDIX;