export const GET_MY_PICKLISTS = 'GET_MY_PICKLISTS';
export const SET_MY_PICKLISTS = 'SET_MY_PICKLISTS';
export const SET_LOADING_GET_MY_PICKLISTS = 'SET_LOADING_GET_MY_PICKLISTS';
export const FILL_PARTS_INTO_PICKLIST = 'FILL_PARTS_INTO_PICKLIST';
export const GET_PICKLIST = 'GET_PICKLIST';
