/**
 * Where is My Part Actions
 */

const SCREEN_APPENDIX = '_WIMP'

export const GET_MY_PICKLISTS = 'GET_MY_PICKLISTS' + SCREEN_APPENDIX;

export const SET_CURRENT_PICKLIST = 'SET_CURRENT_PICKLIST' + SCREEN_APPENDIX;

export const SET_PARTS = 'SET_PARTS' + SCREEN_APPENDIX;

export const SET_LOADING_PARTS = 'SET_LOADING_PARTS' + SCREEN_APPENDIX;

export const GET_PICKLIST_TUBE_LOCATIONS = 'GET_PICKLIST_TUBE_LOCATIONS' + SCREEN_APPENDIX;